pipeline {
    agent { label 'worker' }

    environment {
        AWS_REGION = 'us-west-2'
        ECR_REPO = 'shree-seeds-fertilizers'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Build') {
            steps { sh 'mvn clean package -DskipTests' }
        }
        stage('Test') {
            steps { sh 'mvn test' }
        }
        stage('Docker Build') {
            steps { sh 'docker build -t $ECR_REPO:$IMAGE_TAG .' }
        }
        stage('ECR Push') {
            steps {
                sh '''
                  AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
                  ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO
                  aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                  aws ecr describe-repositories --repository-names $ECR_REPO --region $AWS_REGION >/dev/null 2>&1 || aws ecr create-repository --repository-name $ECR_REPO --region $AWS_REGION
                  docker tag $ECR_REPO:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
                  docker push $ECR_URI:$IMAGE_TAG
                  echo $ECR_URI:$IMAGE_TAG > image.txt
                '''
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                  aws eks update-kubeconfig --region $AWS_REGION --name my-cluster-krushna
                  kubectl apply -f k8s/namespace.yaml
                  kubectl apply -f k8s/configmap.yaml
                  kubectl apply -f k8s/secret.yaml
                  kubectl apply -f k8s/deployment.yaml
                  kubectl apply -f k8s/service.yaml
                  kubectl apply -f k8s/ingress.yaml
                  kubectl apply -f k8s/hpa.yaml
                '''
            }
        }
    }
}
