spring.application.name=shree-seeds-fertilizers
server.port=8080
# For AWS RDS, set these as environment variables:
# DB_URL, DB_USERNAME, DB_PASSWORD
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/shree_seeds}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
